language: cpp

os:
  - osx

compiler:
  - clang

branches:
  except:
    - windows
    - linux

before_script:
  - brew update
  - brew install ninja
  - python3 -m pip install meson
  - git submodule update --init --recursive
  - mkdir build
  - python3 -m mesonbuild setup build

script:
  - cd build
  - ninja
  - ninja test