language: cpp

os:
  - osx

osx_image: xcode11.3

compiler:
  - clang

branches:
  except:
    - windows
    - linux

before_script:
  - brew update
  - brew install ninja
  - python3 -m pip install meson
  - git submodule update --init --recursive
  - mkdir build

script:
  - meson setup build
  - cd build
  - ninja
  - ninja test