version: 1.0.{build}
os: Visual Studio 2019

branches:
  except:
    - linux
    - macos

install:
  - cmd: git submodule update --init --recursive

build_script:
  - cmd: CC=clang-cl
  - cmd: CXX=clang-cl
  - cmd: mkdir build
  - cmd: meson setup build
  - cmd: cd build
  - cmd: ninja
  - cmd: ninja test

test: off

# Uncomment to enable rdp.
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
